### ISSUE TITLE
How to use DragInt2 ?

### ISSUE THREAD

**Issue by cholushkin** [ImGuiNET/ImGui.NET#400] opened 2023-05-21 19:42 UTC
In ImGuiNative.gen.cs there is:
public static extern byte igDragInt2(byte* label, int* v, float v_speed, int v_min, int v_max, byte* format, ImGuiSliderFlags flags);
which expects pointer to values, for igDragInt2 it expects 2 values

On C# side In ImGui.gen.cs there is
public static bool DragInt2(string label, ref int v);
which expects ref to 1 integer value

What is a right way to pass array of 2 integers to DragInt2 ?

**Comment by zaafar** [comment] 2023-05-21 23:06
duplicate of https://github.com/ImGuiNET/ImGui.NET/issues/181

**Closed by zaafar** 2023-05-21 23:06 UTC
