### ISSUE TITLE
DockBuilder functions or structs are not existing

### ISSUE THREAD

**Issue by Trippixyz** [ImGuiNET/ImGui.NET#403] opened 2023-05-30 19:24 UTC
Hi!
Upon trying to call functions like `DockBuilderAddNode` or `DockBuilderDockWindow` I found out that they simply are not there. Even after using the CodeGenerator they didnt exist.

**Comment by zaafar** [comment] 2023-05-30 21:02
duplicate of https://github.com/ImGuiNET/ImGui.NET/issues/249

**Closed by zaafar** 2023-05-30 21:02 UTC
